# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-17 16:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Enfant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=30, null=True)),
                ('Prenom', models.CharField(max_length=30, null=True)),
                ('Nom_de_compte', models.CharField(max_length=30, null=True)),
                ('mot_de_passe', models.CharField(max_length=42, null=True)),
                ('parent', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Lieu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=30, null=True)),
                ('Adresse', models.CharField(max_length=100, null=True)),
                ('Code_postal', models.CharField(max_length=8, null=True)),
                ('Numero_rue', models.CharField(max_length=5, null=True)),
                ('Ville', models.CharField(max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=30, null=True)),
                ('utilisateur', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
