# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-18 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basededonnee', '0008_disponibilite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilite',
            name='debut',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='disponibilite',
            name='fin',
            field=models.TimeField(null=True),
        ),
    ]
