# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-22 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basededonnee', '0009_auto_20160118_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='disponibilite',
            name='jour',
            field=models.CharField(choices=[('lundi', 'Lundi'), ('mardi', 'Mardi'), ('mercredi', 'Mercredi'), ('jeudi', 'Jeudi'), ('vendredi', 'Vendredi'), ('samedi', 'Samedi')], max_length=8, null=True),
        ),
    ]
