# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-28 20:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basededonnee', '0010_disponibilite_jour'),
    ]

    operations = [
        migrations.CreateModel(
            name='Journee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.CharField(choices=[('lundi', 'Lundi'), ('mardi', 'Mardi'), ('mercredi', 'Mercredi'), ('jeudi', 'Jeudi'), ('vendredi', 'Vendredi'), ('samedi', 'Samedi')], default='Lundi', max_length=8)),
                ('Matin', models.TimeField(default=datetime.time(0, 0))),
                ('Soir', models.TimeField(default=datetime.time(0, 0))),
                ('LieuM', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='LieuM', to='basededonnee.Lieu')),
                ('LieuS', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='LieuS', to='basededonnee.Lieu')),
            ],
        ),
    ]
