# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-05 13:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basededonnee', '0013_enfant_edt'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='Ville',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='basededonnee.Lieu'),
        ),
        migrations.AlterField(
            model_name='lieu',
            name='proprietaire',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
