# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-05 14:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basededonnee', '0014_auto_20160205_1336'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parent',
            old_name='Ville',
            new_name='Lieu',
        ),
    ]
