# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-05 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basededonnee', '0015_auto_20160205_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='Email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='parent',
            name='Nom',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='parent',
            name='Prenom',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
