# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-11 15:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basededonnee', '0016_auto_20160205_1425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parent',
            name='Lieu',
        ),
        migrations.AddField(
            model_name='disponibilite',
            name='Lieu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='basededonnee.Lieu'),
        ),
    ]
