# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-14 10:38
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basededonnee', '0019_auto_20160214_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='Numero_Telephone',
            field=models.CharField(max_length=15, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
