# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-14 10:40
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basededonnee', '0020_auto_20160214_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='Couleur_voiture',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='parent',
            name='Immatriculation',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='parent',
            name='Nombre_place',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='parent',
            name='Numero_Telephone',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Format de numéro de téléphone incorrect.', regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
