# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-14 11:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basededonnee', '0023_parent_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='photo',
            field=models.ImageField(default='media/nope.jpg', upload_to='/media/'),
        ),
    ]
