# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-15 07:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basededonnee', '0024_auto_20160214_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='lieu',
            name='x',
            field=models.DecimalField(decimal_places=10, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='lieu',
            name='y',
            field=models.DecimalField(decimal_places=10, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='parent',
            name='photo',
            field=models.ImageField(default='Media/nope.jpg', upload_to='/Media/'),
        ),
    ]
