# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-15 13:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basededonnee', '0026_auto_20160215_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecole',
            name='Adresse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='basededonnee.Lieu'),
        ),
    ]
