# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-16 10:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basededonnee', '0027_auto_20160215_1312'),
    ]

    operations = [
        migrations.CreateModel(
            name='Covoiturage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Passager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('covoit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='basededonnee.Covoiturage')),
                ('enf', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='basededonnee.Enfant')),
            ],
        ),
        migrations.RemoveField(
            model_name='ecole',
            name='Nom',
        ),
        migrations.AlterField(
            model_name='lieu',
            name='Nom',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='parent',
            name='photo',
            field=models.FileField(default='Media/nope.jpg', upload_to=''),
        ),
        migrations.AddField(
            model_name='covoiturage',
            name='conducteur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='basededonnee.Parent'),
        ),
    ]
