# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-17 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basededonnee', '0029_auto_20160217_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='disponibilite',
            name='retour',
            field=models.NullBooleanField(),
        ),
    ]
