# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-17 15:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basededonnee', '0030_disponibilite_retour'),
    ]

    operations = [
        migrations.CreateModel(
            name='covUtil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.CharField(choices=[('lundi', 'Lundi'), ('mardi', 'Mardi'), ('mercredi', 'Mercredi'), ('jeudi', 'Jeudi'), ('vendredi', 'Vendredi'), ('samedi', 'Samedi')], max_length=8, null=True)),
                ('horaireDepart', models.TimeField(null=True)),
                ('horaireArrivee', models.TimeField(null=True)),
                ('LieuArrivee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='basededonnee.Lieu')),
                ('LieuDepart', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='LieuDepart', to='basededonnee.Lieu')),
                ('Usr', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='basededonnee.Enfant')),
            ],
        ),
    ]
