# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-17 16:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basededonnee', '0032_auto_20160217_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='covutil',
            name='Usr',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
